name: Cypress Tests

on: [push, pull_request]

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Criar pasta de evidências
        run: mkdir -p cypress/evidences

      - name: Run Cypress headless
        run: npx cypress run
        env:
          CYPRESS_TELEMETRY_DISABLED: 1
          CYPRESS_VIDEO: true
          CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

      - name: Upload evidences
        uses: actions/upload-artifact@v4
        with:
          name: evidences
          path: cypress/evidences
